### ISSUE TITLE
Use the latest actions.

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#244]
`actions/checkout@v2` and `actions/setup-python@v2`  are out of date.

https://github.com/aistairc/aiaccel/blob/05eb2538ba5748f9231245e18054e938f3bee6da/.github/workflows/actions.yaml#L14-L18

In particular, `actions/setup-python@v3` will not work after 31st May 2023 due to change in the github actions.

> Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Therefore, it is better to use the latest version.
```yaml
 - name: Checkout 
   uses: actions/checkout@v3 
  
 - name: Set Up ${{ matrix.python-version }} 
   uses: actions/setup-python@v4
```
