### ISSUE TITLE
Problems with setting a initial value in config.yaml

### ISSUE THREAD

**Issue by 3bisuoka** [aistairc/aiaccel#320]
**Describe the bug**

There are two points I would like to report.

- aiaccel allows a initial value to be set outside the range of [lower, upper] as shown below.

**config.yaml**
```yaml
generic:
  workspace: "./work"
  job_command: "python user.py"
  python_file: "./user.py"
  function: "main"
  batch_job_timeout: 600
  enabled_variable_name_argumentation: True

resource:
  # type: "abci"
  # type: "local"
  type: "python_local"
  num_workers: 1

optimize:
  search_algorithm: "aiaccel.optimizer.RandomOptimizer"
  goal: "minimize"
  trial_number: 10
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.1
      upper: 5.0
      log: false
      initial: 0.01
```    

In addtion to that, 
- aiaccel does not generate 0.2 but np.log(0.2) as the initial value when I change "log: false" and "initial: 0.01" to "log: true" and "0.2", respectively. np.log(0.2) is outside the range of [0.1, 5.0].

```diff
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.1
      upper: 5.0
-     log: false
+     log: true
-     initial: 0.01
+     initial: 0.2
```    

The above specifications confused me when I set parameters which can not be negative such as the learning rate.
