### ISSUE TITLE
When resume NelderMead optimization, occur ValueError

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#33]
**Describe the bug**
When resume neldermead optimization, occur ValueError and stop aiaccel.

**To Reproduce**
1. Executed aiaccel using below config file.
```
generic:
  workspace: "./work"
  job_command: "python user.py"
  batch_job_timeout: 14400

resource:
  type: "abci"
  num_node: 6

ABCI:
  group: "[group]"
  job_script_preamble: "./job_script_preamble.sh"
  job_execution_options: ""

optimize:
  search_algorithm: "nelder-mead"
  goal: "minimize"
  trial_number: 100
  rand_seed: 42
  parameters:
    -
      name: "lr"
      type: "uniform_float"
      lower: 0.0001
      upper: 0.1
    -
      name: "weight_decay"
      type: "uniform_float"
      lower: 1.0e-6
      upper: 1.0e-3
```

2. An unexpected error (over the file capacity limit) occurred and aiaccel stopped.
3. Executed aiaccel using resume option.
4. Occured ValueError and stoped aiaccel.

**Screenshots**
console
![Screenshot from 2022-08-08 12-37-24](https://user-images.githubusercontent.com/105629713/183593641-876d99a2-f685-4b25-96cb-1d6cb280ef31.png)

log
[error_NM.log](https://github.com/aistairc/aiaccel/files/9288300/error_NM.log)

**Desktop (please complete the following information):**
 - OS: linux (ABCI)

**Additional context**
sample work directory
[work_sample.tar.gz](https://github.com/aistairc/aiaccel/files/9288311/work_sample.tar.gz)
