### ISSUE TITLE
The neldermead may search for out-of-range coordinates.

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#335]
**Describe the bug**
neldermead では範囲外の座標の計算結果はinfとして扱うが、範囲外でもinfとして扱わず、通常通り計算を行う場合がある。

user.py
```
def main(p):
    X = p["x1"]
    Y = p["x2"]
    # Ackley function
    y = -20*np.exp(-0.2*np.sqrt(0.5*(X**2+Y**2)))-np.exp(0.5 *
                                                         (np.cos(2*np.pi*X)+np.cos(2*np.pi*Y)))+np.e+20
    return float(y)

```
config.yaml
```
optimize:
  search_algorithm: "aiaccel.optimizer.NelderMeadOptimizer"
  goal: "minimize"
  trial_number: 20
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
    -
      name: "x2"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
```

上記設定で実行した結果
```
trial_id,x1,x2,objective
000000,1.8727005942368125,4.75357153204958,[11.575169214302525]
000001,3.6599697090570253,2.993292420985183,[11.209799234362702]
000002,0.7800932022121826,0.7799726016810132,[4.4008786102853]
000003,2.567362317032395,-0.980306509383384,[inf]
000004,2.046366024935708,3.3201020216913393,[9.892812425477638]
000005,-0.8335104819091348,1.1067822023871692,[4.376646477695299]
000006,-3.080250577392215,0.16352709308816227,[7.782610393483804]
000007,-2.0997833046326604,-1.4333472176231568,[inf]
000008,1.009828692543616,2.131739711862715,[6.0811555401575745]
000009,-1.0632459722405683,-0.24498490779453252,[inf]
000010,0.49156002634756996,1.5375585569484032,[6.427069426971769]
000011,-0.026708639848476157,0.9433774020340913,[2.6011086837290307]
000012,0.08815910531724058,1.6192609571249421,[5.7561242510962565]
000013,-0.9483782270748515,0.4308986472963183,[4.437322557994051]
000014,-0.6892438939768285,0.7279892247534743,[4.5872103905410455]
000015,-0.4301095608788055,1.0250798022106302,[4.585719285925002]
000016,0.030725232734382213,1.2813191795795167,[4.552530361677867]
000017,0.43412615376471153,1.1996167794029775,[5.280627097747129]
000018,-0.21405063221792622,1.068714046508717,[3.8138703015795024]
000019,-0.27148450480078457,0.7307722689632914,[3.925793588913244]
```

例えば trial_id = 000005 の座標 x1 = -0.8335104819091348 は 0 < x1 < 5 を満たしていない（範囲外なのでobjective = [inf]として扱われるべき）にも関わらず、
objective = [4.376646477695299] となっており、通常通りに計算されている。

**Expected behavior**
範囲外の座標の計算結果はすべてinfとして扱う。
