### ISSUE TITLE
Is NelderMead optimizer working as expected?

### ISSUE THREAD

**Issue by 3bisuoka** [aistairc/aiaccel#355]
**Describe the bug**

　現行のmainブランチのNelderMead optimizerを用いてexamples/sphere (initialおよびlower, upperは下記configファイルのように変更) に対してハイパラ最適化を行ったところ，以前のNelderMead optimizerによるものとは異なる計算結果が返ってきました(添付Screenshot参照)．これは意図したとおりの結果でしょうか．

　下記のnelder_mead_optimizer.py内のrun_optimizer関数の処理では，生成されたハイパラが[lower, upper]からはみ出したときにはそのトライアルではobjectiveの値を出さずにスキップして次のトライアルに進むようです．いまトライアル数を50に設定すると，以前のプログラムではboundaryを超えるようなハイパラを除外して50個のトライアルが実行されるのに対して，現行のプログラムではboundaryを超えてしまったハイパラも含めて50個のトライアルが実行されているように見えます．

https://github.com/aistairc/aiaccel/blob/0c2559fedee384694cc7ca72d8082b8bed4dc7ad/aiaccel/optimizer/nelder_mead_optimizer.py#L147-L183

**To Reproduce**

　下記config.yamlの設定でNelderMead optimizerを使用してハイパラ最適化を行う．

**Screenshot**

Fig 1. 現行バージョンのNelderMeadによるハイパラ最適化の計算結果．
<img width="832" alt="neldermead1" src="https://github.com/aistairc/aiaccel/assets/117958864/b7f1b488-0862-42b1-b266-b462a2a4b209">

Fig 2. 以前のバージョンのNelderMeadによるハイパラ最適化の計算結果．
<img width="889" alt="neldermead2" src="https://github.com/aistairc/aiaccel/assets/117958864/95459bcb-dde1-4394-99bb-91cb3c75d293">

**Additional context**
**config.yaml**
```yaml

generic:
  workspace: "./work"
  job_command: "python user.py"
  # python_file: "./user.py"
  # function: "main"
  batch_job_timeout: 600
  enabled_variable_name_argumentation: True
  logging_level: INFO

resource:
  # type: "abci"
  type: "local"
  # type: "python_local"
  num_workers: 4

optimize:
  search_algorithm: "aiaccel.optimizer.NelderMeadOptimizer"
  goal: "minimize"
  trial_number: 50
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.001
      upper: 1e+3
      initial: 1e+2
      # log: true
    -
      name: "x2"
      type: "uniform_float"
      lower: 0.001
      upper: 1e+3
      initial: 1e+2
      # log: true
    -
      name: "x3"
      type: "uniform_float"
      lower: 0.001
      upper: 1e+3
      initial: 1e+2
      # log: true
    -
      name: "x4"
      type: "uniform_float"
      lower: 0.001
      upper: 1e+3
      initial: 1e+2
      # log: true
    -
      name: "x5"
      type: "uniform_float"
      lower: 0.001
      upper: 1e+3
      # log: true
      initial: 10.0
```
